"""
Django settings for jiaowu project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-stfq%^qfgj@qtje(2l*=8t=33ih0726a7!$k*pxz9#ai^vcn5g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'education',  # 新增：注册 education 应用
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jiaowu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jiaowu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'jiaowu3',  # 你的 MySQL 数据库名（需提前在 MySQL 中创建）
        'USER': 'root',       # MySQL 用户名
        'PASSWORD': '123456789', # MySQL 密码
        'HOST': '127.0.0.1',  # 数据库地址
        'PORT': '3306',       # 端口
        'OPTIONS': {
            'charset': 'utf8mb4',  # 支持 emoji 字符
        }
    }
}

# 解决 MySQL 在 Python3 下的兼容问题（在文件底部添加）
import pymysql
pymysql.install_as_MySQLdb()


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []  # 确保为空列表，无任何验证器配置
# {
#     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     'OPTIONS': {
#         'message': '该密码与用户名或其他个人信息过于相似。'  # 中文提示
#     }
# },
# {
#     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     'OPTIONS': {
#         'min_length': 8,
#         'message': '该密码太短。必须包含至少%(min_length)d个字符。'  # 中文提示
#     }
# },
# {
#     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     'OPTIONS': {
#         'message': '该密码过于常见。'  # 中文提示
#     }
# },
# {
#     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     'OPTIONS': {
#         'message': '该密码完全由数字组成。'  # 中文提示
#     }
#



# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Add at the bottom of the file
LOGIN_REDIRECT_URL = '/student_list/'  # Redirect after login
LOGIN_URL = 'education:login'  # New: Custom login URL name
