# Generated by Django 4.2.22 on 2025-06-10 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='权限名称')),
                ('code', models.CharField(help_text='示例：view_student（查看）, edit_student（编辑）', max_length=100, verbose_name='对应代码')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限管理',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('permissions', models.ManyToManyField(to='education.permission', verbose_name='对应权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色管理',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1, verbose_name='性别')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('mobile', models.CharField(blank=True, max_length=11, verbose_name='电话')),
                ('roles', models.ManyToManyField(blank=True, to='education.role', verbose_name='角色')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生管理',
            },
        ),
    ]
